### PR TITLE
增加代码生成器生成model时对于lombok的支持

### PR DESCRIPTION
**Pull request by finira**
在model代码生成时，可以直接生成lombok的
`@Getter@Setter@ToString@Accessors(chain = true)`
四类注解，使用者在插件配置项中增加
`<property name="lombok" value="Getter,Setter,ToString,Accessors"/>`
即可生成对应包含注解的model类，生成Getter,Setter注解会取消原本对应get和set方法的生成。
其他注解暂未扩展。

### CODE REVIEW

**Comment by abel533** [comment]
编译发现错误：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mapper-generator: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[158,47] cannot find symbol
[ERROR] symbol:   class Method
[ERROR] location: class tk.mybatis.mapper.generator.MapperPlugin
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[159,76] cannot find symbol
[ERROR] symbol:   class IntrospectedColumn
[ERROR] location: class tk.mybatis.mapper.generator.MapperPlugin
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[161,53] package Plugin does not exist
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[170,47] cannot find symbol
[ERROR] symbol:   class Method
[ERROR] location: class tk.mybatis.mapper.generator.MapperPlugin
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[171,76] cannot find symbol
[ERROR] symbol:   class IntrospectedColumn
[ERROR] location: class tk.mybatis.mapper.generator.MapperPlugin
[ERROR] /home/travis/build/abel533/Mapper/generator/src/main/java/tk/mybatis/mapper/generator/MapperPlugin.java:[173,53] package Plugin does not exist

**Comment by abel533** [comment]
我找时间看看。

**Comment by eacdy** [comment]
需要这个特性！！！目前项目大规模使用lombok & Mapper。
这个特性完成省的自己搞了。

**Comment by eacdy** [comment]
我觉得至少得有`@Data` `@Builder` `@AllArgsConstructor` `@NoArgsConstructor`

**Comment by abel533** [comment]
已合并，解决了一个 lombok 版本BUG。

**Comment by zhouxianjun** [comment]
callSuper 这个版本还没发布吗？

**Comment by zhouxianjun** [comment]
@abel533

**Pull request merged**
